### ISSUE TITLE
What is the format for entering MQTT info into preference for a headless install?

### ISSUE THREAD

**Issue by YenLegion** [joshuar/go-hass-agent#235]
Couldn't find an example in the readme. Thanks.

**Comment by joshuar** [comment]
Hey there, thanks for trying out Go Hass Agent!

I haven't yet exposed command-line options for configuring MQTT, but, you can just edit the configuration file directly and add the appropriate entries. The configuration file should be located at `~/.config/com.github.joshuar.go-hass-agent/preferences.toml` and the following lines configure MQTT:

```toml
'mqtt.password' = 'password'  # optional, only if needed
'mqtt.user' = 'user'   # optional, only if needed
'mqtt.server' = 'tcp://localhost:1883'
'mqtt.enabled' = true
```

Hope this helps.
